"""ORM models. Settings use a key-value table so adding a new setting never alters the
schema — the setting's type/default/description live in core.settings_defs, not in columns.

Column comments document intent (SQLite ignores them at the DB level, but they travel with
the model and apply on engines that support comments, e.g. Postgres)."""

from typing import Optional

from sqlalchemy.orm import Mapped, mapped_column

from core.db import Base


class SessionCategory(Base):
    __tablename__ = "session_categories"

    id: Mapped[str] = mapped_column(
        primary_key=True,
        comment="Category id, generated by the server",
    )
    name: Mapped[str] = mapped_column(
        comment="Label shown as the group header in the chat list",
    )
    position: Mapped[float] = mapped_column(
        comment="Sort key among categories; fractional so a move rewrites one row",
    )
    color: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="Accent name from the shared palette; NULL uses the default one",
    )


class SessionPlacement(Base):
    __tablename__ = "session_placement"

    session_id: Mapped[str] = mapped_column(
        primary_key=True,
        comment="Transcript id on disk; rows whose session is gone are pruned",
    )
    category_id: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="Category holding the chat; NULL keeps it in the uncategorised group",
    )
    position: Mapped[float] = mapped_column(
        comment="Sort key inside the category, only read while the order is manual",
    )


class TrashedSession(Base):
    __tablename__ = "trashed_sessions"

    session_id: Mapped[str] = mapped_column(
        primary_key=True,
        comment="Transcript id; the file itself waits under the projects dir's .trash",
    )
    project_key: Mapped[str] = mapped_column(
        comment="Project it was deleted from, and the one it goes back to on restore",
    )
    title: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="What to call it in the trash list, since the transcript is out of the scan",
    )
    path: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="Working directory it belonged to, shown next to the title",
    )
    deleted_at: Mapped[float] = mapped_column(
        comment="Epoch seconds it was thrown away; the trash itself never expires",
    )
    category_id: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="Category it sat in, kept here so restoring puts it back where it was",
    )
    position: Mapped[Optional[float]] = mapped_column(
        nullable=True,
        comment="Its sort key inside that category, restored along with it",
    )


class ProjectMeta(Base):
    __tablename__ = "project_meta"

    project_key: Mapped[str] = mapped_column(
        primary_key=True,
        comment="Encoded project directory under ~/.claude/projects",
    )
    path: Mapped[str] = mapped_column(
        comment="Working directory the project stands for",
    )
    name: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="Display name; NULL falls back to the last folder of the path",
    )


class Setting(Base):
    __tablename__ = "settings"

    key: Mapped[str] = mapped_column(
        primary_key=True,
        comment="Setting key; matches an entry in the code registry (settings_defs.SETTINGS)",
    )
    value: Mapped[Optional[str]] = mapped_column(
        nullable=True,
        comment="JSON-encoded override value; NULL means the code-defined default is used",
    )
    description: Mapped[str] = mapped_column(
        default="",
        comment="Human-readable description of the setting, synced from the code registry",
    )
